# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# Application Name
# ===============================
spring.application.name=jwt-auth

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/jwt_bd
spring.datasource.username=root
spring.datasource.password=MySql@1608
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT Configuration
# ===============================
jwt.secret=Z0VJQkF6cDg4c1d6R2lQSmZVY0xZbE9kN2hWZ0Z4c3F4YlZVZkR0Zw==
jwt.expiration=3600000

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=DEBUG
